### ISSUE TITLE
Suggestion: add demo's

### ISSUE THREAD

**Issue by Annelein** [animo/awesome-self-sovereign-identity#22]
Maybe we can add a list of demo's you can do, for example we do list the Lissi Wallet but not their demo.

**Comment by TimoGlastra** [comment]
Sounds good! Can you gather all demo's out there an make a PR? 

I think it would be nice to include both high level demo's (e.g demo.animo.id) and lower level demo's (e.g. afj demo).

Here a list of demo's @anagoessens gathered: https://twitter.com/animosolutions/status/1495800868112896010?s=21

**Comment by Annelein** [comment]
Yes!
